# Copyright (c) .NET Foundation and contributors. All rights reserved. Licensed under the Microsoft Reciprocal License. See LICENSE.TXT file in the project root for full license information.

branches:
  only:
    - master
    - develop

image: Visual Studio 2022

version: 0.0.0.{build}
configuration: Release

init:
  - git config --global core.autocrlf true

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_XMLDOC_MODE: skip
  WixSkipVsDevCmd: 1
  RuntimeTestsEnabled: true

install:
  - reg add HKLM\Software\Policies\Microsoft\Windows\Installer /t REG_SZ /v Logging /d voicewarmupx /f
  - reg add HKLM\Software\WOW6432Node\Policies\Microsoft\Windows\Installer /t REG_SZ /v Logging /d voicewarmupx /f

build_script:
  - src\build_official.cmd

after_build:
  - 7z a "build\testresults.zip" @src\testresultfilelist.txt

on_finish:
  - wevtutil epl Application build\logs\Application.evtx /q:"Event/System/TimeCreated[timediff(@SystemTime) <= 86400000]"
  - wevtutil epl System build\logs\System.evtx /q:"Event/System/TimeCreated[timediff(@SystemTime) <= 86400000]"
  - ps: 7z a ('temp_logs_' + (Get-Date).tostring("yyyyMMddHHmmss") + '.zip') $env:TEMP\*.log $env:TEMP\..\*.log
  - ps: 7z a ('build_logs_' + (Get-Date).tostring("yyyyMMddHHmmss") + '.zip') build\logs\ build\logs\TestResults\
  - ps: Push-AppveyorArtifact temp_logs_*.zip
  - ps: Push-AppveyorArtifact build_logs_*.zip

test: off

pull_requests:
  do_not_increment_build_number: true

nuget:
  disable_publish_on_pr: true

skip_branch_with_pr: true
skip_tags: true

artifacts:
  - path: build\artifacts
    name: artifacts
    type: zip

notifications:
- provider: Slack
  incoming_webhook:
    secure: p5xuu+4x2JHfwGDMDe5KcG1k7gZxqYc4jWVwvyNZv5cvkubPD2waJs5yXMAXZNN7Z63/3PWHb7q4KoY/99AjauYa1nZ4c5qYqRPFRBKTHfA=

for:
- branches:
    only:
      - master

  environment:
    SigningUser:
      secure: s+b2kuhi/AlE8ZYFsNVHFLfgJOwi0fIKMCOP+xL++8U=
    SigningSecret:
      secure: h0urCGu3+ArelfLcW0JvB82rc7dkPqedVSxXmMbQ+dc=
