name: Build WiX Toolset v4

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # - name: Configure Visual Studio
      #   shell: cmd
      #   run: ./src/vs_config.cmd

      - name: Build wix4
        shell: cmd
        run: ./src/build_official.cmd
        env:
          RuntimeTestsEnabled: true
          SigningUser:  ${{ github.ref == 'refs/heads/master' && secrets.WIX_SIGNING_USER || '' }}
          SigningSecret:  ${{ github.ref == 'refs/heads/master' && secrets.WIX_SIGNING_SECRET || '' }}

      - name: Validate test results
        shell: cmd
        run: 7z a build\testresults.zip @src\testresultfilelist.txt

      - name: Save build
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/artifacts/

      - name: Collect integration test logs
        if: always()
        shell: cmd
        run: 7z a "build\logs\test_burn_%GITHUB_RUN_ID%.zip" "%TEMP%\*.log" "%TEMP%\..\*.log"

      - name: Export Application event log
        if: always()
        shell: cmd
        run: wevtutil epl Application build\logs\Application.evtx /q:"Event/System/TimeCreated[timediff(@SystemTime) <= 86400000]"

      - name: Export System event log
        if: always()
        shell: cmd
        run: wevtutil epl System build\logs\System.evtx /q:"Event/System/TimeCreated[timediff(@SystemTime) <= 86400000]"

      # Do NOT publish logs on `master` branch as they may contain secrets in them.
      - name: Save logs
        if: github.ref != 'refs/heads/master' && (success() || failure())
        uses: actions/upload-artifact@v2
        with:
          name: logs_${{ github.run_id }}
          path: build/logs/

      - name: Push to GitHub Packages
        if: github.event_name == 'push' && github.repository_owner == 'wixtoolset' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/develop')
        run: dotnet nuget push "build/artifacts/**/*.nupkg" --source https://nuget.pkg.github.com/wixtoolset/index.json --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate
