name: Build WiX Toolset v4

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

env:
  DOTNET_NOLOGO: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  NUGET_XMLDOC_MODE: skip

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Visual Studio
        shell: cmd
        run: ./src/vs_config.cmd

      - name: Build wix4
        shell: cmd
        run: ./src/build_official.cmd
        env:
          RuntimeTestsEnabled: true
          SigningUser:  ${{ github.ref == 'refs/heads/master' && secrets.WIX_SIGNING_USER || '' }}
          SigningSecret:  ${{ github.ref == 'refs/heads/master' && secrets.WIX_SIGNING_SECRET || '' }}

      - name: Save build
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: build/artifacts/

      - name: Validate Test Results
        shell: cmd
        run: 7z a build\testresults.zip @src\testresultfilelist.txt

      - name: Zip temp logs
        shell: cmd
        run: 7z a "build\logs\test_burn_%GITHUB_RUN_ID%.zip" "%TEMP%\*.log" "%TEMP%\..\*.log"
        if: always()

      - name: Save logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: logs_${{ github.run_id }}
          path: build/logs/
